global:
  domain: eaafdf0.stage.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: maheshlakkammanavar
    tag: latestt1
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    service-manager:
      serviceInstanceName: service-manager
  image:
    repository: incident-management-srv
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    ASYNC_UPLOAD: "true"
    destinations: '[{"forwardAuthToken":true,"name":"srv-api","url":"https://incidents-srv-mahesh.eaafdf0.stage.kyma.ondemand.com"}]'
  image:
    repository: "incident-management-html5-deployer"
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: shared
    xsappname: incident-managementt-{{ .Release.Namespace }}
    oauth2-configuration:
      redirect-uris:
        - https://*.eaafdf0.stage.kyma.ondemand.com/**
service-manager:
  serviceOfferingName: service-manager
  servicePlanName: container
saas-registry:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parameters:
    displayName: incident-managementt
    description: A simple CAP projectt.
    category: "CAP Application"
    appUrls:
      onSubscriptionAsync: true
      onUnSubscriptionAsync: true
      onUpdateDependenciesAsync: true
      callbackTimeoutMillis: 300000
      getDependencies: https://{{ .Release.Name }}-sidecar-{{ .Release.Namespace }}.{{ .Values.global.domain }}/-/cds/saas-provisioning/dependencies
      onSubscription: https://{{ .Release.Name }}-sidecar-{{ .Release.Namespace }}.{{ .Values.global.domain }}/-/cds/saas-provisioning/tenant/{tenantId}
    xsappname: incident-managementt-{{ .Release.Namespace }}
    appName: incident-managementt-{{ .Release.Namespace }}
sidecar:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    saas-registry:
      serviceInstanceName: saas-registry
    service-manager:
      serviceInstanceName: service-manager
    html5-apps-repo-host:
      serviceInstanceName: html5-apps-repo-host  
  image:
    repository: incident-management-sidecar
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
  env:
    SUBSCRIPTION_URL: https://${tenant_subdomain}-{{ .Release.Name }}-srv-{{ .Release.Namespace }}.{{ .Values.global.domain }}
html5-apps-repo-runtime: 
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-runtime  

